=== se1983/HTW-Verteilte_Systeme/Ueb5/VS_Ueb5_XML_JSON/src/main/resources/planeSchmaUniVS.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<xs:element name="booking" type="RootElementType"/>


<xs:complexType name="RootElementType">
    <xs:sequence>
        <xs:element name="originplace" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="destinationplace" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="departure" type="departureType" />
        <xs:element name="arrival" type="arrivalType"/>
        <xs:element name="passengers" type="passengersType" />
        <xs:element name="cabinclass" type="xs:string" />
        <xs:element name="price" type="xs:float" />
    </xs:sequence>
</xs:complexType>


<xs:complexType name="departureType" >
    <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="date" type="xs:date"/>
            <xs:element name="time" type="xs:time"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="arrivalType" >
    <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="date" type="xs:date"/>
            <xs:element name="time" type="xs:time"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="passengersType" >
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="passenger" type="passengerType" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="passengerType" >
    <xs:sequence>
        <xs:element name="sex" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
        <xs:element name="packages" type="xs:boolean"/>
        <xs:element name="name" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

</xs:schema>

=== se1983/HTW-Verteilte_Systeme/Ueb5/VS_Ueb5_XML_JSON/src/main/resources/plane.xml
<?xml version="1.0" encoding="UTF-8"?>

<booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./planeSchmaUniVS.xsd">

    <originplace>TXL</originplace>
    <destinationplace>MUC</destinationplace>

    <departure>
        <date>2002-09-24</date>
        <time>09:00:00</time>
    </departure>
    
    
    <arrival>
        <date>2002-09-24</date>
        <time>10:00:00</time>
    </arrival>
    
    
    <passengers>
        <passenger>
            <sex>male</sex>
            <country>de</country>
            <packages>false</packages>
            <name>Ferdinand Freibeuter</name>
        </passenger>
        
        <passenger>
            <sex>female</sex>
            <country>at</country>
            <packages>true</packages>
            <name>Karla Kauftgern</name>
        </passenger>
        
    </passengers>
    
    <cabinclass>Economy</cabinclass>
    
    <price>202.22</price>
</booking>
